# Generated by Django 5.1.6 on 2025-02-16 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_room_participants'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.RemoveField(
            model_name='message',
            name='name',
        ),
    ]
